/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiInsightsRouteImport } from './routes/ai-insights'
import { Route as FieldAnalysisRouteImport } from './routes/field-analysis'
import { Route as ScenarioLabRouteImport } from './routes/scenario-lab'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldAnalysisRoute = FieldAnalysisRouteImport.update({
  id: '/field-analysis',
  path: '/field-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioLabRoute = ScenarioLabRouteImport.update({
  id: '/scenario-lab',
  path: '/scenario-lab',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/field-analysis': typeof FieldAnalysisRoute
  '/scenario-lab': typeof ScenarioLabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/field-analysis': typeof FieldAnalysisRoute
  '/scenario-lab': typeof ScenarioLabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/field-analysis': typeof FieldAnalysisRoute
  '/scenario-lab': typeof ScenarioLabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-insights' | '/field-analysis' | '/scenario-lab'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-insights' | '/field-analysis' | '/scenario-lab'
  id: '__root__' | '/' | '/ai-insights' | '/field-analysis' | '/scenario-lab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiInsightsRoute: typeof AiInsightsRoute
  FieldAnalysisRoute: typeof FieldAnalysisRoute
  ScenarioLabRoute: typeof ScenarioLabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-insights': {
      id: '/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-analysis': {
      id: '/field-analysis'
      path: '/field-analysis'
      fullPath: '/field-analysis'
      preLoaderRoute: typeof FieldAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario-lab': {
      id: '/scenario-lab'
      path: '/scenario-lab'
      fullPath: '/scenario-lab'
      preLoaderRoute: typeof ScenarioLabRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiInsightsRoute: AiInsightsRoute,
  FieldAnalysisRoute: FieldAnalysisRoute,
  ScenarioLabRoute: ScenarioLabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
